apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: youtube
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        dapr.io/app-id: payment-service
        dapr.io/app-port: "5001"
        dapr.io/enabled: "true"
    spec:
      containers:
      - name: payment-service
        image: payment-service:1.0.0-rc1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: youtube
spec:
  selector:
    app: payment-service
  ports:
  - port: 5001
    targetPort: 5001
