apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-service
  namespace: youtube
spec:
  selector:
    matchLabels:
      app: not-service
  template:
    metadata:
      labels:
        app: not-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: not-service
        dapr.io/app-port: "5001"
    spec:
      containers:
      - name: not-service
        image: not-service:1.0.0-rc1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: not-service
  namespace: youtube
spec:
  selector:
    app: not-service
  ports:
  - port: 5001
    targetPort: 5001
